logging:
  config: classpath:log4j2.yml
spring:
  data:
    mongodb:
      host: 192.168.145.132
      port: 27017
      database: MyDB
      username: myUser
      password: 1234
openapi:
  service:
    url: http://openapi.data.go.kr/openapi/service/rest/Covid19
    key: iwmlm2wLyo4%2FWdSG7%2F9OHWYAKMBZ1rn2pbkIs4%2BIVr5QUvSn8x8rTXFITSAkbpeCJqJrN%2BerV8kiH6%2FwNwaiSg%3D%3D

